import { describe, it, expect } from 'vitest';
import {
	SERVICE_AREA_CONTEXT_PATH,
	SERVICE_AREA_VIEWBOX,
	serviceAreaLocalities
} from './service-area';
import { getLocalBusinessSchema, getServiceAreaSchema } from '$lib/utils/seo';
import { ROUTES } from '$lib/config/constants';
import { _paths as sitemapPaths } from '../../routes/sitemap.xml/+server';

/**
 * The map data is generated by scripts/build-service-area-map.mjs. These guard
 * the contract the page and the structured data depend on, so a bad
 * regeneration fails here rather than shipping a blank or misdrawn map.
 */
describe('service area map data', () => {
	it('covers the localities the business serves', () => {
		expect(serviceAreaLocalities).toHaveLength(15);
	});

	it('has a unique GEOID and a drawable path for every locality', () => {
		const geoids = new Set<string>();
		serviceAreaLocalities.forEach(({ geoid, name, path }) => {
			expect(geoid).toMatch(/^\d{5}$/);
			expect(geoids.has(geoid)).toBe(false);
			geoids.add(geoid);
			expect(name).toBeTruthy();
			// A path that survived simplification opens with a moveto and closes
			// its ring; anything less has no area and renders as nothing.
			expect(path.startsWith('M')).toBe(true);
			expect(path.endsWith('Z')).toBe(true);
		});
	});

	it('emits only path commands this map uses', () => {
		// The generator writes an absolute moveto, relative line segments, and a
		// close. A curve, an absolute lineto, or a decimal point would mean the
		// output came from somewhere other than scripts/build-service-area-map.mjs.
		const allowed = /^[MlZ0-9,\- ]+$/;
		serviceAreaLocalities.forEach(({ name, path }) => {
			expect(allowed.test(path), `${name} has unexpected path commands`).toBe(true);
		});
		expect(allowed.test(SERVICE_AREA_CONTEXT_PATH)).toBe(true);
	});

	it('draws every locality inside the declared viewBox', () => {
		// Walking the relative deltas back to absolute positions checks two things
		// at once: that the delta encoding reconstructs, and that the projection
		// and the viewBox agree. If they disagree, part of the map is clipped
		// away with nothing in the markup to show for it.
		const [, , width, height] = SERVICE_AREA_VIEWBOX.split(' ').map(Number);
		expect(width).toBeGreaterThan(0);
		expect(height).toBeGreaterThan(0);

		const check = (label: string, path: string) => {
			for (const subpath of path.split('M').filter(Boolean)) {
				const [start, rest = ''] = subpath.replace('Z', '').split('l');
				let [x, y] = start.split(',').map(Number);

				for (const pair of [start, ...rest.split(' ').filter(Boolean)]) {
					if (pair !== start) {
						const [dx, dy] = pair.split(',').map(Number);
						x += dx;
						y += dy;
					}
					expect(Number.isFinite(x) && Number.isFinite(y), `${label} has a bad point`).toBe(true);
					expect(x, `${label} x`).toBeGreaterThanOrEqual(0);
					expect(x, `${label} x`).toBeLessThanOrEqual(width);
					expect(y, `${label} y`).toBeGreaterThanOrEqual(0);
					expect(y, `${label} y`).toBeLessThanOrEqual(height);
				}
			}
		};

		serviceAreaLocalities.forEach(({ name, path }) => check(name, path));
	});

	it("classifies Virginia's independent cities as cities, not counties", () => {
		// An independent city sits outside any county. Getting this wrong labels
		// Suffolk a county on the page and emits the wrong Schema.org type.
		const kindOf = (name: string) => serviceAreaLocalities.find((l) => l.name === name)?.kind;

		expect(kindOf('Virginia Beach')).toBe('city');
		expect(kindOf('Chesapeake')).toBe('city');
		expect(kindOf('Suffolk')).toBe('city');
		expect(kindOf('Williamsburg')).toBe('city');
		expect(kindOf('Poquoson')).toBe('city');

		expect(kindOf('York')).toBe('county');
		expect(kindOf('James City')).toBe('county');
		expect(kindOf('Isle of Wight')).toBe('county');
		expect(kindOf('King and Queen')).toBe('county');
		expect(kindOf('Henrico')).toBe('county');
	});

	it('includes the enclaved cities so the map has no holes in it', () => {
		// Williamsburg and Poquoson are entirely surrounded by James City and
		// York. Dropping either punches a hole through the middle of the shaded
		// area that reads as a rendering fault rather than a boundary.
		const names = serviceAreaLocalities.map((l) => l.name);
		expect(names).toContain('Williamsburg');
		expect(names).toContain('Poquoson');
	});

	it('draws neighbouring localities behind the served ones', () => {
		// Without the backdrop the served area floats in white space and the gap
		// left by Norfolk, Portsmouth, Hampton and Newport News looks like a
		// hole rather than four cities outside the service area.
		expect(SERVICE_AREA_CONTEXT_PATH.length).toBeGreaterThan(1000);
	});
});

describe('service area structured data', () => {
	it('extends the business node rather than describing a second business', () => {
		// Same @id as the LocalBusiness the layout emits on every page, so the two
		// JSON-LD nodes on this page merge into one entity.
		expect(getServiceAreaSchema()['@id']).toBe(getLocalBusinessSchema()['@id']);
	});

	it('types counties and independent cities differently', () => {
		const areas = getServiceAreaSchema().areaServed;
		expect(areas).toHaveLength(serviceAreaLocalities.length);

		expect(areas).toContainEqual({ '@type': 'AdministrativeArea', name: 'York County' });
		// Schema.org has no county type, so counties are AdministrativeArea; the
		// independent cities genuinely are City.
		expect(areas).toContainEqual({ '@type': 'City', name: 'Virginia Beach' });
	});
});

describe('sitemap coverage', () => {
	it('lists every route in ROUTES', () => {
		// The route table and the sitemap are two copies of one fact. A page added
		// to the nav but not the sitemap is a page search engines have to find on
		// their own.
		Object.values(ROUTES).forEach((route) => {
			expect(sitemapPaths, `${route} is missing from the sitemap`).toContain(route);
		});
	});
});
